# Generated by Django 6.0.4 on 2026-06-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_compra_criado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Barras'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Foto do Item'),
        ),
        migrations.AddField(
            model_name='produto',
            name='localizacao',
            field=models.CharField(blank=True, help_text='Ex: Prateleira A, Gaveta 2', max_length=100, null=True, verbose_name='Localização / Prateleira'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='alerta_validade',
            field=models.BooleanField(default=True, help_text='Se ativo, monitora a validade dos lotes comprados.', verbose_name='Alerta de Validade'),
        ),
    ]
