# Generated by Django 6.0.4 on 2026-06-03 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_produto_codigo_barras_produto_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='compras/documentos/', verbose_name='Arquivo')),
                ('nome', models.CharField(blank=True, max_length=255, verbose_name='Nome do Arquivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='estoque.compra')),
            ],
            options={
                'verbose_name': 'Documento de Compra',
                'verbose_name_plural': 'Documentos de Compras',
                'ordering': ['-criado_em'],
            },
        ),
    ]
