# Generated by Django 6.0.4 on 2026-06-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_documentocompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
        migrations.AddField(
            model_name='compra',
            name='recebido',
            field=models.BooleanField(default=False, verbose_name='Recebido'),
        ),
    ]
