# Generated by Django 6.0.4 on 2026-06-05 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_compra_pago_compra_recebido'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentoestoque',
            name='movimento_origem',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversoes', to='estoque.movimentoestoque'),
        ),
    ]
