# Generated by Django 6.0.4 on 2026-04-17 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('banner', models.ImageField(upload_to='eventos/banners/')),
                ('data_evento', models.DateTimeField()),
                ('local_nome', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('vendas_abertas', 'Vendas Abertas'), ('esgotado', 'Esgotado'), ('cancelado', 'Cancelado'), ('encerrado', 'Encerrado')], default='planejado', max_length=20)),
            ],
            options={
                'ordering': ['data_evento'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.PositiveIntegerField()),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('ativo', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Produtora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(blank=True, max_length=100)),
                ('empresa', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_produtora', to='core.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='produtora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='eventos.produtora'),
        ),
        migrations.CreateModel(
            name='TipoIngresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_disponivel', models.PositiveIntegerField()),
                ('quantidade_vendida', models.PositiveIntegerField(default=0)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_ingresso', to='eventos.lote')),
            ],
        ),
    ]
