# Generated by Django 6.0.4 on 2026-06-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Restaurante')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug/Subdomínio')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp para Reservas/Pedidos')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('venda_online', models.BooleanField(default=False, verbose_name='Venda Online (Delivery/Reservas)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
                'ordering': ['nome'],
            },
        ),
    ]
