# Generated by Django 6.0.4 on 2026-06-28 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestauranteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('proprietario', 'Proprietário'), ('gerente', 'Gerente'), ('atendente', 'Atendente / Garçom')], default='atendente', max_length=30)),
                ('cpf', models.CharField(blank=True, help_text='Formato: 000.000.000-00', max_length=14, null=True, unique=True)),
                ('ativo', models.BooleanField(default=False)),
                ('restaurante', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to='restaurantes.restaurante')),
                ('user', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_restaurante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
