# Generated by Django 6.0.4 on 2026-06-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0002_restauranteusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='cidade_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Cidade'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='especialidade',
            field=models.CharField(blank=True, help_text='Ex: Pizzaria, Massas, Regional', max_length=150, null=True, verbose_name='Especialidade Culinária'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='restaurantes/', verbose_name='Foto Principal'),
        ),
    ]
