# Generated by Django 6.0.4 on 2026-06-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0003_restaurante_cidade_nome_restaurante_especialidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='restaurantes/banners/', verbose_name='Banner / Hero'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='cor_primaria',
            field=models.CharField(blank=True, default='#e11d48', max_length=7, verbose_name='Cor Primária (Hex)'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='cor_secundaria',
            field=models.CharField(blank=True, default='#f97316', max_length=7, verbose_name='Cor Secundária (Hex)'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='descricao',
            field=models.TextField(blank=True, help_text='Aparece no Hero da página pública', null=True, verbose_name='Descrição / Slogan'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='hero_tipo',
            field=models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], default='imagem', max_length=10, verbose_name='Tipo do Hero'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='hero_video',
            field=models.FileField(blank=True, null=True, upload_to='restaurantes/videos/', verbose_name='Vídeo do Hero'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurantes/logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='sobre_banner',
            field=models.ImageField(blank=True, null=True, upload_to='restaurantes/sobre/', verbose_name='Imagem/Foto da Seção Sobre'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='sobre_cor_fundo',
            field=models.CharField(blank=True, default='#f8fafc', max_length=7, verbose_name='Cor de Fundo da Seção Sobre (Hex)'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='sobre_cor_texto',
            field=models.CharField(blank=True, default='#0f172a', max_length=7, verbose_name='Cor do Texto da Seção Sobre (Hex)'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='sobre_midia_tipo',
            field=models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], default='imagem', max_length=10, verbose_name='Tipo de Mídia do Sobre'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='sobre_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Texto da Seção Sobre'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='sobre_titulo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Título da Seção Sobre'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='sobre_video',
            field=models.FileField(blank=True, null=True, upload_to='restaurantes/sobre/', verbose_name='Vídeo da Seção Sobre'),
        ),
    ]
