# Generated by Django 6.0.4 on 2026-06-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0004_restaurante_banner_restaurante_cor_primaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Público / Contato'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='whatsapp_privado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Privado (Contato Naviê)'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp para Reservas/Pedidos (Público)'),
        ),
    ]
