# Generated by Django 6.0.4 on 2026-06-28 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0005_restaurante_email_contato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestauranteAtracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(help_text='Ex: Sábado, 28/06, Todos os dias', max_length=100, verbose_name='Dia da Atração')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Atração')),
                ('texto', models.TextField(verbose_name='Descrição da Atração')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='restaurantes/atracoes/', verbose_name='Imagem da Atração')),
                ('video', models.FileField(blank=True, null=True, upload_to='restaurantes/atracoes/', verbose_name='Vídeo da Atração')),
                ('midia_tipo', models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], default='imagem', max_length=10, verbose_name='Tipo de Mídia')),
                ('cor_fundo', models.CharField(blank=True, default='#0f172a', max_length=7, verbose_name='Cor de Fundo (Hex)')),
                ('cor_texto', models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='Cor do Texto (Hex)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('restaurante', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='atracoes', to='restaurantes.restaurante')),
            ],
            options={
                'verbose_name': 'Atração do Restaurante',
                'verbose_name_plural': 'Atrações do Restaurante',
                'ordering': ['-criado_em'],
            },
        ),
    ]
