# Generated by Django 6.0.4 on 2026-06-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0006_restauranteatracao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restauranteatracao',
            options={'ordering': ['data', 'horario', '-criado_em'], 'verbose_name': 'Atração do Restaurante', 'verbose_name_plural': 'Atrações do Restaurante'},
        ),
        migrations.AddField(
            model_name='restauranteatracao',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Atração'),
        ),
        migrations.AddField(
            model_name='restauranteatracao',
            name='horario',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário da Atração'),
        ),
    ]
