# Generated by Django 6.0.4 on 2026-07-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0007_alter_restauranteatracao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram (URL)'),
        ),
    ]
