# Generated by Django 6.0.4 on 2026-05-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plataformaconfig_taxa_gateway_percentual'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0, help_text='Total de visualizações da página da empresa'),
        ),
        migrations.AddField(
            model_name='plataformaconfig',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0, help_text='Total de visualizações da página principal do Naviê Vibe'),
        ),
    ]
