# Generated by Django 6.0.4 on 2026-06-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_visualizacoes_plataformaconfig_visualizacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='modalidade_portal',
            field=models.CharField(choices=[('individual', 'Páginas Individuais por Pousada'), ('unificado', 'Portal de Rede Unificado (Uma única página para o grupo)')], default='individual', help_text='Define se a empresa exibe um portal único com todos os hotéis ou páginas independentes.', max_length=20, verbose_name='Modalidade do Portal'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='slug',
            field=models.SlugField(blank=True, help_text='Subdomínio para o portal unificado da empresa. Ex: pousadasramilos', null=True, unique=True, verbose_name='Subdomínio da Rede'),
        ),
    ]
