# Generated by Django 6.0.4 on 2026-06-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_empresa_modalidade_portal_empresa_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='descricao_portal',
            field=models.TextField(blank=True, help_text='Slogan ou descrição principal da rede que aparecerá no topo do portal unificado.', null=True, verbose_name='Descrição/Slogan do Portal'),
        ),
    ]
