# Generated by Django 6.0.4 on 2026-06-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_empresa_descricao_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='hero_tipo',
            field=models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], default='imagem', help_text='Tipo de mídia a ser exibida no cabeçalho/Hero do site', max_length=10, verbose_name='Tipo de Mídia do Hero'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Vídeo curto em loop (MP4 de até 8MB)', null=True, upload_to='empresas/videos/', verbose_name='Vídeo do Hero'),
        ),
    ]
