# Generated by Django 6.0.4 on 2026-06-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_empresa_hero_tipo_empresa_hero_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cor_secundaria',
            field=models.CharField(default='#2563eb', max_length=7, verbose_name='Cor Secundária (Hex)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagem_compartilhamento',
            field=models.ImageField(blank=True, help_text='Imagem para miniatura de compartilhamento nas redes sociais (WhatsApp, Facebook, etc.)', null=True, upload_to='empresas/compartilhamento/', verbose_name='Imagem de Compartilhamento (16:9)'),
        ),
    ]
