# Generated by Django 6.0.4 on 2026-06-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_empresa_cor_secundaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='sobre_banner',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/sobre/', verbose_name='Imagem do Sobre'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sobre_cor_fundo',
            field=models.CharField(default='#f8fafc', max_length=7, verbose_name='Cor de Fundo do Sobre (Hex)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sobre_cor_texto',
            field=models.CharField(default='#0f172a', max_length=7, verbose_name='Cor do Texto do Sobre (Hex)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sobre_midia_tipo',
            field=models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], default='imagem', max_length=10, verbose_name='Tipo de Mídia do Sobre'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sobre_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Texto da Seção Sobre'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sobre_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título da Seção Sobre'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sobre_video',
            field=models.FileField(blank=True, help_text='Vídeo curto em loop (MP4 de até 8MB)', null=True, upload_to='empresas/sobre_videos/', verbose_name='Vídeo do Sobre'),
        ),
    ]
