# Generated by Django 6.0.4 on 2026-07-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_empresa_sobre_banner_empresa_sobre_cor_fundo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Ícone que aparece na aba do navegador. Recomenda-se imagem quadrada (ex: 32x32 ou 64x64px).', null=True, upload_to='empresas/favicons/', verbose_name='Favicon da Rede'),
        ),
    ]
