# Generated by Django 6.0.5 on 2026-06-17 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema', '0010_alter_usuario_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Atividade')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição/Anotações')),
                ('status', models.CharField(choices=[('todo', 'A Fazer'), ('doing', 'Em Andamento'), ('done', 'Concluído')], default='todo', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta')], default='normal', max_length=20)),
                ('data_vencimento', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora limite')),
                ('lembrete', models.DateTimeField(blank=True, null=True, verbose_name='Lembrar em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hospede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to='sistema.cliente', verbose_name='Hóspede')),
                ('pousada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='sistema.pousada', verbose_name='Pousada')),
                ('quarto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to='sistema.quarto', verbose_name='Quarto / Chalé')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to='sistema.reserva', verbose_name='Reserva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'db_table': 'atividades_atividade',
                'ordering': ['data_vencimento', '-prioridade'],
            },
        ),
    ]
