# Generated by Django 6.0.4 on 2026-04-17 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('titulo_original', models.CharField(blank=True, max_length=255)),
                ('duracao_minutos', models.PositiveIntegerField()),
                ('classificacao_indicativa', models.CharField(default='Livre', max_length=20)),
                ('genero', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
                ('poster', models.ImageField(upload_to='filmes/posters/')),
                ('trailer_url', models.URLField(blank=True)),
                ('em_cartaz', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possui_bonbonniere', models.BooleanField(default=True)),
                ('descricao_cinema', models.TextField(blank=True)),
                ('empresa', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cinema', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('capacidade', models.PositiveIntegerField()),
                ('formato_som', models.CharField(default='Dolby Digital 7.1', max_length=100)),
                ('formato_imagem', models.CharField(default='4K Laser', max_length=100)),
                ('ativa', models.BooleanField(default=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='cinema.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField()),
                ('preco_inteira', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_meia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idioma', models.CharField(choices=[('dub', 'Dublado'), ('leg', 'Legendado')], default='dub', max_length=50)),
                ('tecnologia', models.CharField(choices=[('2d', '2D'), ('3d', '3D')], default='2d', max_length=20)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='cinema.filme')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='cinema.sala')),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
                'ordering': ['horario'],
            },
        ),
    ]
