# Generated by Django 6.0.4 on 2026-07-01 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hoteis', '0040_reserva_pagamento_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(help_text='Endereço de e-mail do destinatário', max_length=254)),
                ('assunto', models.CharField(help_text='Assunto do e-mail', max_length=255)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('falha', 'Falha')], default='sucesso', help_text='Status do envio do e-mail', max_length=10)),
                ('erro_mensagem', models.TextField(blank=True, help_text='Detalhes do erro caso o envio tenha falhado', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data e hora do disparo do e-mail')),
                ('reserva', models.ForeignKey(blank=True, help_text='Reserva associada a este e-mail (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='hoteis.reserva')),
            ],
            options={
                'verbose_name': 'Log de E-mail',
                'verbose_name_plural': 'Logs de E-mails',
                'ordering': ['-criado_em'],
            },
        ),
    ]
