# Generated by Django 6.0.4 on 2026-07-01 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacoes', '0001_initial'),
        ('hoteis', '0040_reserva_pagamento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='reserva',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Reserva associada a este e-mail (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='hoteis.reserva'),
        ),
    ]
