# Generated by Django 6.0.4 on 2026-06-03 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrinhoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_id', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(db_index=True, help_text='Ex: hospedagem, cinema, restaurante', max_length=50)),
                ('item_id', models.CharField(db_index=True, help_text='ID do item no carrinho', max_length=100)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('recuperado', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Detalhes específicos (datas de check-in, sessões, ingressos)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrinhos_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_carrinhostatus',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('category', models.CharField(db_index=True, help_text='Ex: hospedagem (frigobar/quarto), cinema, restaurante', max_length=50)),
                ('item_id', models.CharField(db_index=True, help_text='ID do produto/serviço consumido', max_length=100)),
                ('nome', models.CharField(help_text='Nome legível do produto/serviço', max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_registroconsumo',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_id', models.CharField(db_index=True, max_length=255)),
                ('interaction_type', models.CharField(choices=[('page_view', 'Visualização de Página'), ('item_detail', 'Visualização de Detalhe de Item'), ('cart_add', 'Adição ao Carrinho'), ('cart_remove', 'Remoção do Carrinho'), ('checkout_start', 'Início de Checkout'), ('checkout_success', 'Finalização de Compra')], db_index=True, default='page_view', max_length=50)),
                ('category', models.CharField(blank=True, db_index=True, help_text='Ex: hospedagem, cinema, restaurante, parque', max_length=50, null=True)),
                ('item_id', models.CharField(blank=True, db_index=True, help_text='ID do recurso específico (ex: ID do quarto ou filme)', max_length=100, null=True)),
                ('parent_id', models.CharField(blank=True, db_index=True, help_text='ID do recurso pai (ex: ID do hotel ou do cinema)', max_length=100, null=True)),
                ('url', models.TextField(help_text='URL completa da página')),
                ('path', models.CharField(help_text='Caminho relativo da requisição', max_length=255)),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Tempo ativamente gasto na página em segundos')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadados extras da interação (ex: filtros de busca)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacoes_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_userinteraction',
                'ordering': ['-criado_em'],
            },
        ),
    ]
