# Generated by Django 6.0.4 on 2026-04-17 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('hoteis', '0002_quartoimagem_unidadequarto_reserva_bloqueioquarto'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='empresa',
            field=models.OneToOneField(blank=True, db_constraint=False, help_text='A entidade comercial dona desta hospedagem', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_hospedagem', to='core.empresa'),
        ),
    ]
