# Generated by Django 6.0.4 on 2026-05-24 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('hoteis', '0003_hotel_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='empresa',
            field=models.OneToOneField(blank=True, db_constraint=False, help_text='A entidade comercial dona desta hospedagem', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_hospedagem', to='core.empresa'),
        ),

        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
    ]
