# Generated by Django 6.0.4 on 2026-05-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0008_hotel_foto_fundo_hotel_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug da URL customizada (ex: pousadaramilostiangua)', max_length=100, null=True, unique=True),
        ),
    ]
