# Generated by Django 6.0.4 on 2026-05-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0016_reserva_ganho_liquido_plataforma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0, help_text='Total de visualizações da página do hotel'),
        ),
        migrations.AddField(
            model_name='quarto',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0, help_text='Total de visualizações do quarto'),
        ),
    ]
