# Generated by Django 6.0.4 on 2026-05-28 22:46

import hoteis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0017_hotel_visualizacoes_quarto_visualizacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedereserva',
            name='documento_frente',
            field=models.FileField(blank=True, null=True, upload_to=hoteis.models.get_hospede_upload_path),
        ),
        migrations.AddField(
            model_name='hospedereserva',
            name='documento_verso',
            field=models.FileField(blank=True, null=True, upload_to=hoteis.models.get_hospede_upload_path),
        ),
    ]
