# Generated by Django 6.0.4 on 2026-05-29 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0019_reservalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('preparo', 'Em Preparo'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=15)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_servico', to='hoteis.hotel')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_servico', to='hoteis.reserva')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_servico', to='hoteis.unidadequarto')),
            ],
            options={
                'db_table': 'hoteis_pedidoservico',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tipo', models.CharField(choices=[('bebida', 'Bebida'), ('comida', 'Comida'), ('servico', 'Serviço'), ('cortesia', 'Cortesia/Apoio')], default='bebida', max_length=15)),
                ('disponivel', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardapio_consumo', to='hoteis.hotel')),
            ],
            options={
                'db_table': 'hoteis_produtoconsumo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='hoteis.pedidoservico')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='hoteis.produtoconsumo')),
            ],
            options={
                'db_table': 'hoteis_itempedidoservico',
            },
        ),
    ]
