# Generated by Django 6.0.4 on 2026-06-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0021_alter_reservalog_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título Principal')),
                ('subtitulo', models.TextField(blank=True, verbose_name='Subtítulo / Descrição')),
                ('tipo_midia', models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], default='imagem', max_length=10, verbose_name='Tipo de Mídia')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='slides/', verbose_name='Imagem do Slide')),
                ('video', models.FileField(blank=True, null=True, upload_to='slides/videos/', verbose_name='Vídeo do Slide')),
                ('data_texto', models.CharField(blank=True, help_text='Ex: 15 a 18 de Junho', max_length=100, verbose_name='Texto de Data')),
                ('local_texto', models.CharField(blank=True, help_text='Ex: Tianguá, CE', max_length=150, verbose_name='Texto de Localização')),
                ('texto_cta', models.CharField(default='Ver Detalhes', max_length=50, verbose_name='Texto do Botão')),
                ('link_cta', models.CharField(blank=True, help_text='URL de destino', max_length=255, verbose_name='Link do Botão')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Slide da Home',
                'verbose_name_plural': 'Slides da Home',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
