# Generated by Django 6.0.4 on 2026-06-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0022_homeslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Cidade')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('imagem', models.ImageField(upload_to='cidades/', verbose_name='Imagem do Card')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='cidades/banners/', verbose_name='Banner do Hero')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / Slogan')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Restaurante')),
                ('especialidade', models.CharField(help_text='Ex: Pizzaria, Massas, Regional', max_length=150, verbose_name='Especialidade Culinária')),
                ('imagem', models.ImageField(upload_to='restaurantes/', verbose_name='Foto Principal')),
                ('cidade_nome', models.CharField(db_index=True, max_length=100, verbose_name='Nome da Cidade')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp de Contato')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
                'ordering': ['nome'],
            },
        ),
    ]
