# Generated by Django 6.0.4 on 2026-06-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0023_cidade_restaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='cor_secundaria',
            field=models.CharField(default='#2563eb', help_text='Cor secundária em formato Hexadecimal (ex: #2563eb)', max_length=7),
        ),
        migrations.AddField(
            model_name='hotel',
            name='imagem_compartilhamento',
            field=models.ImageField(blank=True, help_text='Imagem para miniatura de compartilhamento (WhatsApp, Instagram, etc.)', null=True, upload_to='hoteis/compartilhamento/'),
        ),
    ]
