# Generated by Django 6.0.4 on 2026-06-03 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        ('hoteis', '0024_hotel_cor_secundaria_hotel_imagem_compartilhamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoconsumo',
            name='estoque_produto',
            field=models.ForeignKey(blank=True, help_text='Vincular ao estoque físico para dedução automática ao consumir.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_consumo_vinculados', to='estoque.produto'),
        ),
    ]
