# Generated by Django 6.0.4 on 2026-06-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0025_produtoconsumo_estoque_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='venda_online',
            field=models.BooleanField(default=True, help_text='Se ativado, permite reservas e pagamentos online pelo site. Se desativado, o botão de reserva direciona para contato via WhatsApp.'),
        ),
    ]
