# Generated by Django 6.0.4 on 2026-06-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0026_hotel_venda_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='consumo_trafego_gb',
            field=models.DecimalField(decimal_places=2, default=14.2, help_text='Consumo atual de tráfego no mês em GB', max_digits=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='limite_trafego_gb',
            field=models.PositiveIntegerField(default=100, help_text='Limite de tráfego mensal alocado em GB'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='taxa_fixa_navie',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Taxa fixa cobrada pelo Naviê por reserva (R$)', max_digits=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='taxa_percentual_navie',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Comissão percentual cobrada pelo Naviê (%)', max_digits=5),
        ),
    ]
