# Generated by Django 6.0.4 on 2026-06-16 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0027_hotel_consumo_trafego_gb_hotel_limite_trafego_gb_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_fixa_padrao', models.DecimalField(decimal_places=2, default=15.0, help_text='Taxa fixa padrão do sistema por reserva (R$)', max_digits=10)),
                ('taxa_percentual_padrao', models.DecimalField(decimal_places=2, default=10.0, help_text='Comissão percentual padrão do sistema (%)', max_digits=5)),
                ('limite_trafego_padrao', models.PositiveIntegerField(default=100, help_text='Limite padrão de tráfego em GB')),
            ],
            options={
                'verbose_name': 'Configuração Geral do Sistema',
                'verbose_name_plural': 'Configurações Gerais do Sistema',
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='usar_tarifas_faixa',
            field=models.BooleanField(default=False, help_text='Se ativado, utiliza a tabela de faixas de valor para calcular a taxa da diária'),
        ),
        migrations.CreateModel(
            name='HotelAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('ip_origem', models.GenericIPAddressField()),
                ('dispositivo', models.TextField()),
                ('campo_alterado', models.CharField(max_length=100)),
                ('valor_antigo', models.TextField(blank=True, null=True)),
                ('valor_novo', models.TextField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='hoteis.hotel')),
                 ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Alteração do Hotel',
                'verbose_name_plural': 'Logs de Alteração de Hotéis',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='HotelDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='hoteis/documentos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='hoteis.hotel')),
            ],
            options={
                'verbose_name': 'Documento do Hotel',
                'verbose_name_plural': 'Documentos do Hotel',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='HotelTarifaFaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_minimo', models.DecimalField(decimal_places=2, help_text='Valor mínimo da diária', max_digits=10)),
                ('valor_maximo', models.DecimalField(decimal_places=2, help_text='Valor máximo da diária', max_digits=10)),
                ('taxa_fixa', models.DecimalField(decimal_places=2, default=0.0, help_text='Taxa fixa em R$', max_digits=10)),
                ('taxa_percentual', models.DecimalField(decimal_places=2, default=0.0, help_text='Taxa em %', max_digits=5)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas_faixa', to='hoteis.hotel')),
            ],
            options={
                'verbose_name': 'Faixa de Tarifa',
                'verbose_name_plural': 'Faixas de Tarifas',
                'ordering': ['valor_minimo'],
            },
        ),
        migrations.CreateModel(
            name='HotelTermoAdesao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao_termo', models.CharField(default='1.0', max_length=50)),
                ('data_aceite', models.DateTimeField(auto_now_add=True)),
                ('ip_origem', models.GenericIPAddressField()),
                ('dispositivo', models.TextField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_adesao', to='hoteis.hotel')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aceite de Termo',
                'verbose_name_plural': 'Aceites de Termos',
                'ordering': ['-data_aceite'],
            },
        ),
    ]
