# Generated by Django 6.0.4 on 2026-06-22 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0029_alter_hotelauditlog_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Seção')),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo')),
                ('tipo', models.CharField(choices=[('texto_imagem', 'Texto com Imagem'), ('galeria', 'Galeria de Fotos'), ('atracoes', 'Grade de Atrações / Atividades'), ('video', 'Vídeo em Destaque')], default='texto_imagem', max_length=20, verbose_name='Tipo de Layout')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Texto / Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='hoteis/secoes/', verbose_name='Imagem de Destaque')),
                ('video_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL de Vídeo (YouTube/Vimeo ou MP4)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes', to='hoteis.hotel')),
            ],
            options={
                'verbose_name': 'Seção do Hotel',
                'verbose_name_plural': 'Seções do Hotel',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='HotelSecaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título/Legenda')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição/Detalhes')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Individual (R$)')),
                ('imagem', models.ImageField(upload_to='hoteis/secoes/itens/', verbose_name='Foto do Item')),
                ('link_cta', models.CharField(blank=True, help_text='Link para compra de ingresso ou WhatsApp', max_length=255, null=True, verbose_name='Link de Ação / Compras')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='hoteis.hotelsecao')),
            ],
            options={
                'verbose_name': 'Item da Seção',
                'verbose_name_plural': 'Itens da Seção',
                'ordering': ['ordem'],
            },
        ),
    ]
