# Generated by Django 6.0.4 on 2026-06-22 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_visualizacoes_plataformaconfig_visualizacoes'),
        ('hoteis', '0030_hotelsecao_hotelsecaoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='empresa',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A entidade comercial dona desta hospedagem', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoteis', to='core.empresa'),
        ),
    ]
