# Generated by Django 6.0.4 on 2026-06-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0031_alter_hotel_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsecaoitem',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='hoteis/secoes/itens/videos/', verbose_name='Vídeo do Item'),
        ),
        migrations.AlterField(
            model_name='hotelsecao',
            name='tipo',
            field=models.CharField(choices=[('texto_imagem', 'Texto com Imagem'), ('galeria', 'Galeria de Fotos'), ('atracoes', 'Grade de Atrações / Atividades'), ('video', 'Vídeo em Destaque'), ('destaques', 'Carrossel de Destaques')], default='texto_imagem', max_length=20, verbose_name='Tipo de Layout'),
        ),
        migrations.AlterField(
            model_name='hotelsecaoitem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='hoteis/secoes/itens/', verbose_name='Foto do Item'),
        ),
    ]
