# Generated by Django 6.0.4 on 2026-06-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0032_hotelsecaoitem_video_alter_hotelsecao_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsecao',
            name='link_cta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link de Ação'),
        ),
        migrations.AddField(
            model_name='hotelsecao',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço/Valor'),
        ),
        migrations.AddField(
            model_name='hotelsecao',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='hoteis/secoes/videos/', verbose_name='Vídeo da Seção'),
        ),
    ]
