# Generated by Django 6.0.4 on 2026-06-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0033_hotelsecao_link_cta_hotelsecao_preco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Ordem de exibição no portal unificado do grupo'),
        ),
    ]
