# Generated by Django 6.0.4 on 2026-06-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0034_hotel_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadequarto',
            name='disponivel',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='unidadequarto',
            name='justificativa_indisponivel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidadequarto',
            name='motivo_indisponivel',
            field=models.CharField(blank=True, choices=[('limpeza', 'Limpeza'), ('manutencao', 'Manutenção'), ('outro', 'Outro')], max_length=50, null=True),
        ),
    ]
