# Generated by Django 6.0.4 on 2026-06-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0036_hotel_como_chegar_hotel_endereco_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='venda_online',
            field=models.BooleanField(default=False, help_text='Se ativado, permite reservas e pagamentos online pelo site. Se desativado, o botão de reserva direciona para contato via WhatsApp.'),
        ),
    ]
