# Generated by Django 6.0.4 on 2026-06-29 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_empresa_sobre_banner_empresa_sobre_cor_fundo_and_more'),
        ('hoteis', '0037_alter_hotel_venda_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoPagoConexao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_user_id', models.CharField(max_length=100, verbose_name='ID da Conta Mercado Pago do Hoteleiro')),
                ('access_token', models.CharField(max_length=255, verbose_name='Access Token do Parceiro')),
                ('refresh_token', models.CharField(max_length=255, verbose_name='Refresh Token para Renovação')),
                ('token_expira_em', models.DateTimeField(verbose_name='Data de Expiração do Token')),
                ('data_conexao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mp_conexao', to='core.empresa')),
            ],
        ),
    ]
