# Generated by Django 6.0.4 on 2026-06-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0038_mercadopagoconexao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MercadoPagoConexao',
        ),
    ]
