# Generated by Django 6.0.4 on 2026-06-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0039_delete_mercadopagoconexao'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='pagamento_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID do Pagamento no Gateway'),
        ),
    ]
