# Generated by Django 6.0.4 on 2026-07-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0040_reserva_pagamento_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Ícone que aparece na aba do navegador para esta pousada específica. Recomenda-se imagem quadrada (ex: 32x32 ou 64x64px).', null=True, upload_to='hoteis/favicons/', verbose_name='Favicon da Pousada'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='imagem_card',
            field=models.ImageField(blank=True, help_text='Imagem que aparece no card de listagem desta pousada na página inicial. Se não informada, será usado o banner.', null=True, upload_to='hoteis/cards/', verbose_name='Imagem do Card (Vitrine)'),
        ),
    ]
