"""
Django settings for navievibe project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carregar variáveis do arquivo .env local, se existir
env_file = BASE_DIR / '.env'
if env_file.exists():
    with open(env_file, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                key, val = line.split('=', 1)
                os.environ[key.strip()] = val.strip()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6^j*32n^cu7t0b1ldy0p$@4@!n1mbe5-(y%58tx9xzz1yktrh6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Requisito para allauth
    'rest_framework',
    'core',
    'hoteis',
    'api',
    'parceiros',
    'cinema',
    'eventos',
    'parques',
    'clientes',
    'sas',
    'analytics',
    
    # Login Social / OAuth (django-allauth)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.apple',
    'allauth.socialaccount.providers.microsoft',
    'sslserver',
    'vouchers',
    'financeiro',
    'estoque',
    'administracao',
    'restaurantes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'analytics.middleware.TrackerMiddleware',
    'django.middleware.common.CommonMiddleware',
    'core.middleware.SubdomainMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'hoteis.middleware.PartnerHotelMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Requisito para allauth
]

ROOT_URLCONF = 'navievibe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'hoteis.context_processors.carrinho',
            ],
        },
    },
]

WSGI_APPLICATION = 'navievibe.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

USE_POSTGRES = os.getenv('USE_POSTGRES', 'False') == 'True'

if USE_POSTGRES:
    DB_PASSWORD = os.getenv('DB_PASSWORD', 'sua_senha_segura')
    DB_HOST = os.getenv('DB_HOST', '127.0.0.1')
    DB_PORT = os.getenv('DB_PORT', '5432')
    DB_USER = os.getenv('DB_USER', 'navievibe_user')
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'navievibe_default',
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
        },
        'hospedagem': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'navievibe_hospedagem',
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
        },
        'cinema': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'navievibe_cinema',
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
        },
        'eventos': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'navievibe_eventos',
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
        },
        'parques': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'navievibe_parques',
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
        },
        'parceiros': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'navievibe_parceiros',
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
        },
        'restaurantes': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'navievibe_restaurantes',
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
        },
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        },
        'hospedagem': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db_hospedagem.sqlite3',
        },
        'cinema': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db_cinema.sqlite3',
        },
        'eventos': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db_eventos.sqlite3',
        },
        'parques': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db_parques.sqlite3',
        },
        'parceiros': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db_parceiros.sqlite3',
        },
        'restaurantes': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db_restaurantes.sqlite3',
        },
    }

DATABASE_ROUTERS = ['core.routers.NavieVibeRouter']

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

# django-allauth - Configurações Gerais (Padrão Moderno v65+)
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_UNIQUE_EMAIL = True
LOGIN_REDIRECT_URL = '/clientes/painel/'
LOGOUT_REDIRECT_URL = '/'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Fortaleza'

USE_I18N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

FIXTURE_DIRS = [
    BASE_DIR / 'data_dumps',
]

# Media files (Uploads of Logos, Banners, Videos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Google Cloud / Google Maps API Integration
GOOGLE_API_KEY = "AIzaSyDnaMUm_EFwesiaLTYw823UaN-IbXoLo5k"


# Integração Oficial Mercado Pago (Checkout Transparente)
MERCADOPAGO_PUBLIC_KEY = os.environ.get('MERCADOPAGO_PUBLIC_KEY', 'APP_USR-358bd3a8-e2f0-4e9d-b2fd-9e4a673b09a2')
MERCADOPAGO_ACCESS_TOKEN = os.environ.get('MERCADOPAGO_ACCESS_TOKEN', 'APP_USR-4287188570193981-052909-e4fdb78128da8bdc840b1d95a9e9d141-3435684980')

# Evita colisão de sessão quando rodando outros projetos Django em localhost em portas diferentes
SESSION_COOKIE_NAME = 'navievibe_sessionid'

# Redireciona usuários não autenticados para a tela de login customizada do cliente B2C
LOGIN_URL = 'clientes:login_cadastro'

# Configurações de Segurança para Produção (HTTPS atrás de Proxy Nginx)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_DOMAIN = '.navievibe.com'

# Armazena mensagens na sessão do banco de dados (evita cookies duplicados/presos no navegador)
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'





