# Generated by Django 6.0.4 on 2026-06-01 07:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hoteis', '0021_alter_reservalog_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita (Entrada de Caixa)'), ('despesa', 'Despesa (Saída de Caixa)')], db_index=True, help_text="Determina a direção do fluxo de caixa: 'receita' aumenta o saldo, 'despesa' reduz o saldo.", max_length=15, verbose_name='Tipo')),
                ('categoria', models.CharField(choices=[('diarias', 'Diárias e Hospedagens (Marketplace Naviê)'), ('walk_in', 'Balcão / Reservas Diretas (Hóspede walk-in sem comissão)'), ('frigobar', 'Consumos de Frigobar (Bebidas/Comidas consumidas no quarto)'), ('room_service', 'Serviço de Quarto / Copa (Pedidos de refeição/serviços)'), ('spa_lazer', 'Lazer & Experiências (Massagens, passeios, aluguéis)'), ('outro_receita', 'Outras Receitas e Ajustes Positivos'), ('salarios', 'Folha de Pagamento (Salários e comissões da equipe)'), ('manutencao', 'Manutenção Predial / Infraestrutura (Reparos, pintura, limpeza)'), ('energia_agua', 'Contas de Consumo (Energia elétrica, água, internet, gás)'), ('amenities', 'Amenities e Brindes (Shampoos, sabonetes, mimos)'), ('taxa_marketplace', 'Comissões Naviê / OTAs (Taxa da plataforma)'), ('outro_despesa', 'Outras Despesas e Perdas de Caixa')], db_index=True, help_text='A categorização contábil exata da transação para geração de DRE operacional.', max_length=30, verbose_name='Categoria')),
                ('valor', models.DecimalField(decimal_places=2, help_text='O valor financeiro nominal em reais (R$) associado à transação.', max_digits=10, verbose_name='Valor (R$)')),
                ('descricao', models.CharField(help_text="Uma descrição curta explicando a natureza do lançamento (ex: 'Compra de toalhas novas').", max_length=255, verbose_name='Descrição')),
                ('data', models.DateField(db_index=True, default=datetime.date.today, help_text='A data contábil de competência em que o evento financeiro ocorreu.', verbose_name='Data Competência')),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data e hora exata em que o registro físico foi inserido no banco de dados.')),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, help_text='O atendente, recepcionista ou gerente humano que cadastrou a transação no sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financeiro_lancamentos', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(help_text='O estabelecimento hoteleiro multitenant proprietário desta transação contábil.', on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_financeiras', to='hoteis.hotel')),
                ('reserva', models.ForeignKey(blank=True, help_text='Opcional. A reserva de hospedagem associada a este lançamento (útil para auditoria de estadias).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_financeiras', to='hoteis.reserva')),
            ],
            options={
                'verbose_name': 'Transação Financeira',
                'verbose_name_plural': 'Transações Financeiras',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
