# Generated by Django 6.0.4 on 2026-06-01 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacaofinanceira',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='O atendente, recepcionista ou gerente humano que cadastrou a transação no sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financeiro_lancamentos', to=settings.AUTH_USER_MODEL),
        ),
    ]
