# Generated by Django 6.0.4 on 2026-06-01 12:59

import datetime
import django.db.models.deletion
import financeiro.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_transacaofinanceira_criado_por'),
        ('hoteis', '0021_alter_reservalog_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacaofinanceira',
            options={'ordering': ['-data_vencimento', '-criado_em'], 'verbose_name': 'Transação Financeira', 'verbose_name_plural': 'Transações Financeiras'},
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, help_text='Código único semântico gerado automaticamente para rastreabilidade de auditoria.', max_length=50, null=True, unique=True, verbose_name='Código da Transação'),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='data_pagamento',
            field=models.DateField(blank=True, db_index=True, help_text='Data opcional em que a transação foi efetivamente paga/compensada.', null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='data_vencimento',
            field=models.DateField(db_index=True, default=datetime.date.today, help_text='Data obrigatória em que o compromisso financeiro deve ser quitado.', verbose_name='Data de Vencimento'),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='unidade',
            field=models.ForeignKey(blank=True, help_text='Opcional. O quarto físico (unidade) associado a esta despesa ou receita.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_financeiras', to='hoteis.unidadequarto'),
        ),
        migrations.AlterField(
            model_name='transacaofinanceira',
            name='data',
            field=models.DateField(blank=True, db_index=True, help_text='A data contábil de competência. Mantida para compatibilidade legada.', null=True, verbose_name='Data Competência (Legado)'),
        ),
        migrations.CreateModel(
            name='AnexoTransacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to=financeiro.models.get_anexo_upload_path)),
                ('codigo', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Código do Anexo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='financeiro.transacaofinanceira')),
            ],
            options={
                'verbose_name': 'Anexo de Transação',
                'verbose_name_plural': 'Anexos de Transações',
                'db_table': 'financeiro_anexotransacao',
            },
        ),
    ]
