# Generated by Django 6.0.4 on 2026-06-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_transacaofinanceira_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacaofinanceira',
            name='categoria',
            field=models.CharField(choices=[('diarias', 'Diárias e Hospedagens (Marketplace Naviê)'), ('walk_in', 'Balcão / Reservas Diretas (Hóspede walk-in sem comissão)'), ('frigobar', 'Consumos de Frigobar (Bebidas/Comidas consumidas no quarto)'), ('room_service', 'Serviço de Quarto / Copa (Pedidos de refeição/serviços)'), ('spa_lazer', 'Lazer & Experiências (Massagens, passeios, aluguéis)'), ('eventos_espaco', 'Eventos & Aluguel de Espaços (Salas, casamentos, reuniões)'), ('estacionamento', 'Taxa de Estacionamento / Garagem'), ('lavanderia', 'Serviços de Lavanderia (Passar, lavar roupas)'), ('cancelamentos_multas', 'Multas de Cancelamento & No-show'), ('outro_receita', 'Outras Receitas e Ajustes Positivos'), ('salarios', 'Folha de Pagamento (Salários e comissões da equipe)'), ('manutencao', 'Manutenção Predial / Infraestrutura (Reparos, pintura, limpeza)'), ('energia_agua', 'Contas de Consumo (Energia elétrica, água, internet, gás)'), ('amenities', 'Amenities e Brindes (Shampoos, sabonetes, mimos)'), ('taxa_marketplace', 'Comissões Naviê / OTAs (Taxa da plataforma)'), ('marketing_anuncios', 'Publicidade & Marketing (Google Ads, redes sociais, impressos)'), ('impostos_taxas', 'Tributos, Impostos & Licenças (IPTU, DAS, taxas municipais)'), ('ti_escritorio', 'Tecnologia & Escritório (Softwares, papéis, computadores)'), ('enxoval_lavanderia', 'Enxoval & Lavanderia Externa (Lençóis, toalhas, higienização)'), ('tarifas_bancarias', 'Tarifas Bancárias & Taxas de Cartão'), ('outro_despesa', 'Outras Despesas e Perdas de Caixa')], db_index=True, help_text='A categorização contábil exata da transação para geração de DRE operacional.', max_length=30, verbose_name='Categoria'),
        ),
    ]
