# Generated by Django 6.0.5 on 2026-05-27 12:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf_passaporte', models.CharField(max_length=30, unique=True, verbose_name='CPF ou Passaporte')),
                ('telefone_whatsapp', models.CharField(max_length=25, verbose_name='WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pousada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Pousada Ramiros Centro, Pousada Ramiros Praia', max_length=150, verbose_name='Nome da Pousada')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço Completo')),
                ('telefone_whatsapp', models.CharField(help_text='Telefone da pousada que receberá as mensagens de reserva do site', max_length=20, verbose_name='WhatsApp de Contato')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ da Unidade')),
                ('cor_primaria_hex', models.CharField(default='#2563eb', help_text='Código hexadecimal da cor de marca (ex: #2563eb). Alimenta o YIQ contrast no front-end.', max_length=7, verbose_name='Cor Primária (Hexadecimal)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Unidade Ativa')),
            ],
            options={
                'verbose_name': 'Pousada',
                'verbose_name_plural': 'Pousadas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Suíte Presidencial, Chalé Duplo', max_length=150, verbose_name='Nome da Acomodação')),
                ('slug', models.SlugField(blank=True, help_text='URL amigável gerada automaticamente a partir do nome', max_length=180)),
                ('descricao', models.TextField(blank=True, help_text='Texto publicitário exibido ao hóspede no site de vendas', verbose_name='Descrição da Acomodação')),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço da Diária Padrão')),
                ('video_url', models.CharField(blank=True, help_text='Link para vídeo MP4 ou embed (YouTube/Vimeo)', max_length=500, null=True, verbose_name='URL de Vídeo Externo')),
                ('capacidade_adultos', models.PositiveIntegerField(default=2, verbose_name='Capacidade Máxima de Adultos')),
                ('capacidade_criancas', models.PositiveIntegerField(default=0, verbose_name='Capacidade Máxima de Crianças')),
                ('tags', models.CharField(blank=True, default='', help_text='Categorização para buscas por inteligência artificial (ex: Família, Romântico, Serra)', max_length=255, verbose_name='Tags para IA')),
                ('comodidades', models.CharField(blank=True, default='', help_text='Diferenciais separados por vírgula (ex: Ar Condicionado, Wi-Fi, Hidromassagem)', max_length=255, verbose_name='Diferenciais / Comodidades')),
                ('tem_desconto_multidias', models.BooleanField(default=False, verbose_name='Habilitar Desconto Progressivo')),
                ('dias_minimos_desconto', models.IntegerField(default=3, verbose_name='Noites Mínimas para Desconto')),
                ('percentual_desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Percentual de Desconto (ex: 10.00 para 10%)')),
                ('seo_titulo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Título Otimizado (SEO/IA)')),
                ('seo_descricao', models.TextField(blank=True, null=True, verbose_name='Descrição Otimizada (SEO/IA)')),
                ('pousada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='sistema.pousada', verbose_name='Pousada')),
            ],
            options={
                'verbose_name': 'Categoria de Acomodação',
                'verbose_name_plural': 'Categorias de Acomodações',
                'unique_together': {('pousada', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome_completo', models.CharField(blank=True, max_length=255, verbose_name='Nome Completo')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador Global'), ('GERENTE', 'Gerente Geral'), ('RECEPCIONISTA', 'Portaria / Recepção'), ('CAMAREIRA', 'Camareira (Equipe de Limpeza)'), ('MANUTENCAO', 'Técnico de Manutenção')], default='RECEPCIONISTA', max_length=20, verbose_name='Cargo / Função')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('pousada_vinculada', models.ForeignKey(blank=True, help_text='Unidade à qual este funcionário está alocado. Administradores globais podem deixar este campo vazio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='sistema.pousada', verbose_name='Pousada de Atuação')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Ex: 101, Chale 02, Deck Presidencial', max_length=50, verbose_name='Identificador / Número do Quarto')),
                ('status', models.CharField(choices=[('LIVRE', 'Livre (Pronto para Uso)'), ('OCUPADO', 'Ocupado'), ('SUJO', 'Sujo (Aguardando Limpeza)'), ('MANUTENCAO', 'Em Manutenção Física')], default='LIVRE', max_length=20, verbose_name='Status Operacional')),
                ('capacidade_maxima', models.PositiveIntegerField(default=2, help_text='Limite físico rígido de hóspedes neste quarto.', verbose_name='Capacidade Máxima')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartos', to='sistema.categoriaquarto', verbose_name='Categoria de Acomodação')),
                ('pousada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartos', to='sistema.pousada', verbose_name='Pousada')),
            ],
            options={
                'verbose_name': 'Quarto Físico',
                'verbose_name_plural': 'Quartos Físicos',
                'ordering': ['pousada', 'numero'],
                'unique_together': {('pousada', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='QuartoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagem', models.ImageField(upload_to='quartos/galeria/', verbose_name='Arquivo de Imagem')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='sistema.categoriaquarto', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Imagem da Acomodação',
                'verbose_name_plural': 'Imagens das Acomodações',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_checkin', models.DateField(verbose_name='Data de Entrada (Check-in)')),
                ('data_checkout', models.DateField(verbose_name='Data de Saída (Check-out)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Confirmação / Pagamento'), ('CONFIRMADA', 'Reserva Confirmada (Garantida)'), ('HOSPEDADO', 'Hospedado (Check-in Realizado)'), ('FINALIZADA', 'Finalizada (Check-out Realizado)'), ('CANCELADA', 'Reserva Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status da Reserva')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Já Pago')),
                ('canal_origem', models.CharField(choices=[('WEBSITE_WHATSAPP', 'Site Público (Redirecionamento WhatsApp)'), ('WEBSITE_DIRETO', 'Site Público (Venda Direta / Pix Online)'), ('INTEGRACAO_CHATBOT', 'WhatsApp Chatbot Automático'), ('BALCAO', 'Reserva de Balcão (Recepção Interna)')], default='WEBSITE_WHATSAPP', max_length=30, verbose_name='Canal de Origem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='sistema.cliente', verbose_name='Hóspede Responsável')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='sistema.quarto', verbose_name='Quarto Alocado')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-data_checkin'],
            },
        ),
        migrations.CreateModel(
            name='TarefaLimpeza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Limpeza'), ('EM_ANDAMENTO', 'Em Higienização'), ('CONCLUIDA', 'Higienizado e Aprovado')], default='PENDENTE', max_length=20, verbose_name='Status do Serviço')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('camareira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_limpeza', to=settings.AUTH_USER_MODEL, verbose_name='Camareira')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_limpeza', to='sistema.quarto', verbose_name='Quarto')),
            ],
            options={
                'verbose_name': 'Tarefa de Limpeza',
                'verbose_name_plural': 'Tarefas de Limpeza',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='TarefaManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Execução'), ('RESOLVIDA', 'Resolvido')], default='PENDENTE', max_length=20, verbose_name='Status do Chamado')),
                ('descricao_problema', models.TextField(verbose_name='Descrição do Defeito')),
                ('solucao_aplicada', models.TextField(blank=True, null=True, verbose_name='Resolução')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Abertura do Chamado')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_manutencao', to='sistema.quarto', verbose_name='Quarto')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_manutencao', to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Tarefa de Manutenção',
                'verbose_name_plural': 'Tarefas de Manutenção',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='TransacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=20, verbose_name='Tipo de Transação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('categoria', models.CharField(choices=[('DIARIA', 'Faturamento de Diárias'), ('CONSUMO', 'Serviço de Quarto / Consumos Extras'), ('MANUTENCAO', 'Despesa com Manutenção e Insumos'), ('SALARIO', 'Folha de Pagamento de Funcionários'), ('OUTRO', 'Outras Receitas / Despesas Gerais')], default='DIARIA', max_length=30, verbose_name='Classificação')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Efetivação')),
                ('metodo_pagamento', models.CharField(choices=[('PIX', 'Pix instantâneo'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('DINHEIRO', 'Dinheiro em Espécie'), ('TRANSFERENCIA', 'Transferência / Boleto')], default='PIX', max_length=20, verbose_name='Forma')),
                ('pousada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='sistema.pousada', verbose_name='Pousada')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='sistema.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Transação Financeira',
                'verbose_name_plural': 'Transações Financeiras',
                'ordering': ['-data_pagamento'],
            },
        ),
    ]
