# Generated by Django 6.0.5 on 2026-05-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaquarto',
            name='video_arquivo',
            field=models.FileField(blank=True, help_text='Arquivo de vídeo local do tour da acomodação (máx. 30MB)', null=True, upload_to='quartos/videos/', verbose_name='Arquivo de Vídeo Local'),
        ),
    ]
