# Generated by Django 6.0.5 on 2026-05-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_categoriaquarto_video_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaquarto',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Categoria Ativa'),
        ),
    ]
