# Generated by Django 5.0.2 on 2026-05-27 18:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_categoriaquarto_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='checkin_realizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='checkout_realizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='ganho_liquido_plataforma',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ganho Líquido Plataforma'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hospede_cpf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hospede_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hospede_endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hospede_nacionalidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hospede_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hospede_profissao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hospede_rg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hospede_telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='quantidade_hospedes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reserva',
            name='repasse_parceiro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Repasse Líquido ao Parceiro'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='taxa_gateway',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Taxa Gateway Absorvida'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='taxa_servico_plataforma',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Taxa de Serviço Plataforma'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='taxas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='sistema.cliente', verbose_name='Hóspede Responsável'),
        ),
        migrations.CreateModel(
            name='BloqueioQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(db_index=True)),
                ('data_fim', models.DateField(db_index=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='sistema.quarto')),
            ],
        ),
        migrations.CreateModel(
            name='VeiculoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('cor', models.CharField(blank=True, max_length=50)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='veiculo', to='sistema.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='HospedeReserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('rg', models.CharField(blank=True, max_length=50)),
                ('nacionalidade', models.CharField(default='Brasileira', max_length=100)),
                ('profissao', models.CharField(blank=True, max_length=100)),
                ('endereco', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospedes', to='sistema.reserva')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('reserva', 'ordem')},
            },
        ),
    ]
