# Generated by Django 6.0.5 on 2026-05-29 11:43

import django.db.models.deletion
import sistema.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_reserva_atualizado_em_reserva_checkin_realizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedereserva',
            name='documento_frente',
            field=models.FileField(blank=True, null=True, upload_to=sistema.models.get_hospede_upload_path),
        ),
        migrations.AddField(
            model_name='hospedereserva',
            name='documento_verso',
            field=models.FileField(blank=True, null=True, upload_to=sistema.models.get_hospede_upload_path),
        ),
        migrations.CreateModel(
            name='ReservaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=50)),
                ('detalhes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sistema.reserva')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
