# Generated by Django 5.0.2 on 2026-06-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_hospedereserva_documento_frente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pousada',
            name='mapa_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada geográfica de latitude do mapa', max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='pousada',
            name='mapa_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada geográfica de longitude do mapa', max_digits=10, null=True, verbose_name='Longitude'),
        ),
    ]
