# Generated by Django 6.0.5 on 2026-06-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_transacaofinanceira_criado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora_checkin',
            field=models.TimeField(default='14:00', verbose_name='Horário de Entrada (Check-in)'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_checkout',
            field=models.TimeField(default='12:00', verbose_name='Horário de Saída (Check-out)'),
        ),
    ]
