# Generated by Django 6.0.5 on 2026-06-11 15:03

import django.db.models.deletion
import sistema.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_reserva_hora_checkin_reserva_hora_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoHospede',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to=sistema.models.get_documento_hospede_upload_path)),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='sistema.hospedereserva')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
    ]
