# Generated by Django 6.0.5 on 2026-06-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_documentohospede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('DIRECAO', 'Direção'), ('PORTARIA', 'Portaria / Recepção'), ('SERVICO', 'Manutenção / Camareiraria')], default='PORTARIA', max_length=20, verbose_name='Cargo / Função'),
        ),
    ]
