# Generated by Django 5.2.15 on 2026-06-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_alter_usuario_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_titulo', models.CharField(default='O aconchego ideal para recarregar suas energias.', max_length=255, verbose_name='Título do Hero')),
                ('hero_subtitulo', models.TextField(default='Descubra a tranquilidade da serra, a calmaria bucólica do sertão ou a brisa revigorante da praia em nossas unidades de alto padrão.', verbose_name='Subtítulo do Hero')),
                ('hero_video_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL do Vídeo do Hero (Externo)')),
                ('hero_video_arquivo', models.FileField(blank=True, null=True, upload_to='pousadas/videos/', verbose_name='Arquivo de Vídeo do Hero (Local)')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.AddField(
            model_name='pousada',
            name='imagem_destaque',
            field=models.ImageField(blank=True, help_text='Imagem da pousada exibida no carrossel do site público.', null=True, upload_to='pousadas/', verbose_name='Imagem de Destaque'),
        ),
    ]
