# Generated by Django 6.0.4 on 2026-06-01 05:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_empresa_visualizacoes_plataformaconfig_visualizacoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_seguro', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Código Seguro Hash')),
                ('tipo', models.CharField(choices=[('hospedagem', 'Hospedagem (Quarto/Chalé)'), ('show', 'Shows & Eventos (Ingresso)'), ('cinema', 'Ciné Naviê (Bilhete)'), ('parques', 'Parques e Day Use')], max_length=20, verbose_name='Tipo de Voucher')),
                ('object_id', models.CharField(db_index=True, max_length=100, verbose_name='ID do Objeto Relacionado')),
                ('utilizado', models.BooleanField(db_index=True, default=False, verbose_name='Já Utilizado?')),
                ('utilizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Utilizado em')),
                ('titulo_exibicao', models.CharField(max_length=255, verbose_name='Título Principal')),
                ('subtitulo_exibicao', models.CharField(max_length=255, verbose_name='Subtítulo / Empresa')),
                ('nome_beneficiario', models.CharField(max_length=255, verbose_name='Nome do Beneficiário')),
                ('documento_beneficiario', models.CharField(max_length=50, verbose_name='Documento Ocultado')),
                ('detalhes_json', models.JSONField(blank=True, default=dict, verbose_name='Metadados Adicionais')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers_emitidos', to='core.empresa')),
                ('utilizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voucher Universal',
                'verbose_name_plural': 'Vouchers Universais',
                'ordering': ['-criado_em'],
            },
        ),
    ]
