# Generated by Django 6.0.4 on 2026-06-15 20:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('hoteis', '0026_hotel_venda_online'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMomento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estabelecimento_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='clientes/momentos/')),
                ('texto', models.TextField(blank=True, null=True)),
                ('avaliacao', models.PositiveSmallIntegerField(default=5, help_text='Nota de 1 a 5 estrelas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='momentos_curtidos', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='momentos', to='hoteis.reserva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Momento',
                'verbose_name_plural': 'Momentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioMomento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField(max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_momentos', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='clientes.postmomento')),
            ],
            options={
                'verbose_name': 'Comentário de Momento',
                'verbose_name_plural': 'Comentários de Momentos',
                'ordering': ['criado_em'],
            },
        ),
    ]
