# Generated by Django 6.0.4 on 2026-06-15 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_postmomento_comentariomomento'),
        ('hoteis', '0026_hotel_venda_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmomento',
            name='reserva',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='momentos', to='hoteis.reserva'),
        ),
    ]
