# Generated by Django 6.0.4 on 2026-04-17 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('hoteis', '0003_hotel_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_parque', models.TextField()),
                ('horario_abertura', models.TimeField(blank=True, null=True)),
                ('horario_fechamento', models.TimeField(blank=True, null=True)),
                ('empresa', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_parque', to='core.empresa')),
                ('hospedagens_vinculadas', models.ManyToManyField(blank=True, db_constraint=False, related_name='parques_donos', to='hoteis.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='IngressoParque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validade_dias', models.PositiveIntegerField(default=1, help_text='Validade em dias após a compra')),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to='parques.parque')),
            ],
        ),
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='parques/atracoes/')),
                ('preco_adicional', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tem_capacidade_limite', models.BooleanField(default=False)),
                ('capacidade_maxima', models.PositiveIntegerField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atracoes', to='parques.parque')),
            ],
            options={
                'verbose_name': 'Atração',
                'verbose_name_plural': 'Atrações',
            },
        ),
    ]
