# Generated by Django 5.0.2 on 2026-06-05 16:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema', '0007_transacaofinanceira_criado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('icone', models.CharField(default='box', help_text='Nome do ícone Lucide a ser exibido (ex: spray-can, utensils, box).', max_length=50, verbose_name='Ícone Lucide')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_produto', to='sistema.pousada')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField(default=datetime.date.today, verbose_name='Data de Compra')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total (R$)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('recebida', 'Recebida (Entregue no Estoque)'), ('cancelada', 'Cancelada')], default='pendente', max_length=15, verbose_name='Status')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('recebido', models.BooleanField(default=False, verbose_name='Recebido')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_registradas', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='sistema.pousada')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-data_compra', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='compras/documentos/', verbose_name='Arquivo')),
                ('nome', models.CharField(blank=True, max_length=255, verbose_name='Nome do Arquivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='estoque.compra')),
            ],
            options={
                'verbose_name': 'Documento de Compra',
                'verbose_name_plural': 'Documentos de Compras',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Razão Social / Nome')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('cnpj_cpf', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ/CPF')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='sistema.pousada')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='estoque.fornecedor'),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Foto do Item')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Barras')),
                ('localizacao', models.CharField(blank=True, help_text='Ex: Prateleira A, Gaveta 2', max_length=100, null=True, verbose_name='Localização / Prateleira')),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade (UN)'), ('KG', 'Quilo (KG)'), ('LT', 'Litro (LT)'), ('PCT', 'Pacote (PCT)'), ('CX', 'Caixa (CX)'), ('MT', 'Metro (MT)')], default='UN', max_length=10, verbose_name='Unidade de Medida')),
                ('finalidade', models.CharField(choices=[('interno', 'Consumo Interno'), ('venda', 'Venda / Frigobar'), ('ambos', 'Ambos (Consumo & Venda)')], default='interno', max_length=10, verbose_name='Finalidade')),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=2, help_text='Preço cobrado ao hóspede se marcado para venda.', max_digits=10, null=True, verbose_name='Preço de Venda (R$)')),
                ('estoque_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Estoque Atual')),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0.0, help_text='Limite mínimo para disparar alerta de reposição.', max_digits=10, verbose_name='Estoque Mínimo')),
                ('alerta_validade', models.BooleanField(default=True, help_text='Se ativo, monitora a validade dos lotes comprados.', verbose_name='Alerta de Validade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='estoque.categoriaproduto')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='sistema.pousada')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste de Inventário')], max_length=10, verbose_name='Tipo de Movimentação')),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='Quantidade movimentada (sempre positiva).', max_digits=10, verbose_name='Quantidade')),
                ('referencia', models.CharField(blank=True, help_text="Ex: 'Compra #12', 'Consumo do Quarto 101', 'Perda por quebra'.", max_length=255, null=True, verbose_name='Referência / Motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_estoque', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_estoque', to='sistema.pousada')),
                ('movimento_origem', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversoes', to='estoque.movimentoestoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='estoque.produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário (R$)')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal (R$)')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.compra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_compra', to='estoque.produto')),
            ],
            options={
                'verbose_name': 'Item de Compra',
                'verbose_name_plural': 'Itens de Compras',
            },
        ),
        migrations.CreateModel(
            name='ProdutoConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(default='bebida', max_length=20)),
                ('disponivel', models.BooleanField(default=True)),
                ('estoque_produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_consumo', to='estoque.produto')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_consumo', to='sistema.pousada')),
            ],
            options={
                'verbose_name': 'Produto de Consumo',
                'verbose_name_plural': 'Produtos de Consumo',
            },
        ),
    ]
